//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hpapp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MedicalCardNumber { get; set; }
        public string CodeDisease { get; set; }
        public string TitleInsuranceCompany { get; set; }
        public string TitleDisease { get; set; }
        public int IDPolyclinic { get; set; }
        public int IDDistrict { get; set; }
    
        public virtual District District { get; set; }
        public virtual Polyclinic Polyclinic { get; set; }
    }
}
