//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewerlyStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDJewelry { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Commission { get; set; }
        public double TotalPrice { get; set; }
        public int Count { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Jewelry Jewelry { get; set; }
    }
}
