//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewerlyStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SignIn()
        {
            this.Regisration = new HashSet<Regisration>();
        }
    
        public int ID { get; set; }
        public string LogIn { get; set; }
        public string Password { get; set; }
        public string RoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regisration> Regisration { get; set; }
        public virtual Role Role { get; set; }
    }
}
