//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Photo { get; set; }
        public string IDGroup { get; set; }
        public int IDStatus { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int IDGender { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
        public virtual Status Status { get; set; }
    }
}
